### ISSUE TITLE
Different usage modes

### ISSUE THREAD

**Issue by briangru** [tomhollander/TeslaAuth#18]
Hi all, the most recent integration for CAPTCHA changes is very good - I appreciate the work.  However, there are two basic questions we need to answer about the usage pattern for TeslaAuthHelper, caused by integrating that work.

1. Should TeslaAuthHelper be threadsafe?
2. Should one TeslaAuthHelper be usable in multiple regions?  Or should we allocate a new TeslaAuthHelper in each region?

The use of the loginInfo field breaks thread safety.  Multiple outstanding requests would not work well.  This is not a problem for the UI demo app, or a mobile app, but it limits usage in server scenarios.  We can't fully disentangle it easily either - we need a piece of state to pass from the beginning of our login attempt to the end of it.  The only fix I came up with was making the GetLoginUrlForBrowser method have an extra out parameter for the loginInfo, then we change the UI app to save that and pass it into GetTokenAfterLoginAsync. 

The other question is whether we should allow one instance of a TeslaAuthHelper to serve multiple regions (say China and the United States), or whether we should have a unique one per country.  Adding in the client field breaks this, w.r.t. thread safety.  We have a concurrent dictionary mapping TeslaAccountRegion to HttpClient instances.  The CAPTCHA bits we picked up ignore that work.

I suggest we pick a resolution to these two, then we ask everyone contributing to integrate this branch's changes into their own work to minimize future potential merge conflicts.  

I had wanted to make this class threadsafe and usable in multiple regions, but I see that it is a bit of a challenge.  I can make the code work either way, but we should ideally pick one direction.

**Comment by tomhollander** [comment]
Hey @briangru, great questions, and I'll admit to not having given these topics enough thought. 

While I'm trying to make a library that's reusable in different contexts, my immediate use case is a single-user client app where none of this has come up. But, based on the way the library is designed today, I would say:

1. No, the library isn't designed to be threadsafe, as it stores state based on a single user's prior steps
2. No, a single instance isn't designed to support multiple regions, since you need to set the region in the constructor.

Clearly it would be possible to design the library in a different way where the answers to either question could be Yes... but I'm not sure this is necessary. There's effectively no cost to creating a new instance, so I think it should be OK to document it as a non-thread-safe component where each usage needs to create its own instance?

**Comment by briangru** [comment]
Sounds good.  I'll clean up some of the code I added a while back to handle multiple regions simultaneously.
